version: "3"
services:
  # docker-go
  docker-go:
    container_name: docker-go
    build:
      context: ./
    privileged: true
    command: sleep infinity 
    volumes: 
      - "vdatago:/workspace"
    networks:
      - app_net
  # mariadb
  mariadb:
        image: mariadb
        container_name: mariadb
        privileged: true
        ports:
            - "3306:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=123456
        networks:
            - app_net
  redis:
        image: redis
        container_name: redis
        privileged:  true
        networks: 
            - app_net
  
networks:
    app_net:
        external: true

volumes:
    vdatago: 
      name: vdatago