version: "3"
services:
  # docker-go
  docker-go:
    container_name: docker-go
    build:
      context: ./
    privileged: true
    command: sleep infinity 
    volumes: 
      - "vdatago:/workspace"
    networks:
      - app_net
  
networks:
    app_net:
        external: true

volumes:
    vdatago: 
      name: vdatago