version: "3"
services:
  # docker-go
  docker-go:
    container_name: docker-go
    build:
      context: ./
    privileged: true
    command: sleep infinity 
    args: 
      - "VARIANT:1.16"
      - "INSTALL_NODE:true"
      - "NODE_VERSION: lts/*"
    volumes: 
      - "vdatago:/workspace"
    networks:
      - app_net
  
networks:
    app_net:
        external: true

volumes:
    vdatago: 
      name: vdatago