version: "3"
services:
  # docker-go
  docker-go:
    container_name: docker-go
    build:
      context: ./
    volumes:
      - ..:/workspace
    privileged: true
    command: sleep infinity 
    networks:
      - app_net
  # mariadb
  mariadb:
        image: mariadb
        container_name: mariadb
        privileged: true
        ports:
            - "3306:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=123456
        networks:
            - app_net
networks:
    app_net:
        external: true
